### ISSUE TITLE
This remark plugin does not work well with react-markdown

### ISSUE THREAD

**Issue by mrbeardad** [ghostdevv/remark-slug-anchor#2]
![image](https://user-images.githubusercontent.com/54128430/137263408-ddb46490-1cd7-4bc3-9f1f-afb110d2f371.png)

**Comment by ghostdevv** [comment]
Wow ok, do you have a repo I can check out to fix this?

**Comment by ghostdevv** [comment]
This is fixed in `1.0.0` <https://github.com/ghostdevv/remark-slug-anchor/releases/tag/v1.0.0>
Install with `npm i remark-slug-anchor@latest`
